// Generated by scheduler/engine/sitout-generate.mjs: do not edit by hand.
window.schedule11p11r = {
  "playerCount": 11,
  "totalRounds": 11,
  "players": [
    "P1",
    "P2",
    "P3",
    "P4",
    "P5",
    "P6",
    "P7",
    "P8",
    "P9",
    "P10",
    "P11"
  ],
  "rounds": [
    {
      "roundNumber": 1,
      "matches": [
        {
          "court": 1,
          "teams": [
            [
              "P7",
              "P9"
            ],
            [
              "P10",
              "P5"
            ]
          ]
        },
        {
          "court": 2,
          "teams": [
            [
              "P2",
              "P3"
            ],
            [
              "P8",
              "P4"
            ]
          ]
        }
      ],
      "byes": [
        "P6",
        "P1",
        "P11"
      ]
    },
    {
      "roundNumber": 2,
      "matches": [
        {
          "court": 1,
          "teams": [
            [
              "P11",
              "P2"
            ],
            [
              "P3",
              "P9"
            ]
          ]
        },
        {
          "court": 2,
          "teams": [
            [
              "P6",
              "P7"
            ],
            [
              "P1",
              "P8"
            ]
          ]
        }
      ],
      "byes": [
        "P10",
        "P5",
        "P4"
      ]
    },
    {
      "roundNumber": 3,
      "matches": [
        {
          "court": 1,
          "teams": [
            [
              "P4",
              "P6"
            ],
            [
              "P7",
              "P2"
            ]
          ]
        },
        {
          "court": 2,
          "teams": [
            [
              "P10",
              "P11"
            ],
            [
              "P5",
              "P1"
            ]
          ]
        }
      ],
      "byes": [
        "P3",
        "P9",
        "P8"
      ]
    },
    {
      "roundNumber": 4,
      "matches": [
        {
          "court": 1,
          "teams": [
            [
              "P8",
              "P10"
            ],
            [
              "P11",
              "P6"
            ]
          ]
        },
        {
          "court": 2,
          "teams": [
            [
              "P3",
              "P4"
            ],
            [
              "P9",
              "P5"
            ]
          ]
        }
      ],
      "byes": [
        "P7",
        "P2",
        "P1"
      ]
    },
    {
      "roundNumber": 5,
      "matches": [
        {
          "court": 1,
          "teams": [
            [
              "P1",
              "P3"
            ],
            [
              "P4",
              "P10"
            ]
          ]
        },
        {
          "court": 2,
          "teams": [
            [
              "P7",
              "P8"
            ],
            [
              "P2",
              "P9"
            ]
          ]
        }
      ],
      "byes": [
        "P11",
        "P6",
        "P5"
      ]
    },
    {
      "roundNumber": 6,
      "matches": [
        {
          "court": 1,
          "teams": [
            [
              "P5",
              "P7"
            ],
            [
              "P8",
              "P3"
            ]
          ]
        },
        {
          "court": 2,
          "teams": [
            [
              "P11",
              "P1"
            ],
            [
              "P6",
              "P2"
            ]
          ]
        }
      ],
      "byes": [
        "P4",
        "P10",
        "P9"
      ]
    },
    {
      "roundNumber": 7,
      "matches": [
        {
          "court": 1,
          "teams": [
            [
              "P9",
              "P11"
            ],
            [
              "P1",
              "P7"
            ]
          ]
        },
        {
          "court": 2,
          "teams": [
            [
              "P4",
              "P5"
            ],
            [
              "P10",
              "P6"
            ]
          ]
        }
      ],
      "byes": [
        "P8",
        "P3",
        "P2"
      ]
    },
    {
      "roundNumber": 8,
      "matches": [
        {
          "court": 1,
          "teams": [
            [
              "P2",
              "P4"
            ],
            [
              "P5",
              "P11"
            ]
          ]
        },
        {
          "court": 2,
          "teams": [
            [
              "P8",
              "P9"
            ],
            [
              "P3",
              "P10"
            ]
          ]
        }
      ],
      "byes": [
        "P1",
        "P7",
        "P6"
      ]
    },
    {
      "roundNumber": 9,
      "matches": [
        {
          "court": 1,
          "teams": [
            [
              "P6",
              "P8"
            ],
            [
              "P9",
              "P4"
            ]
          ]
        },
        {
          "court": 2,
          "teams": [
            [
              "P1",
              "P2"
            ],
            [
              "P7",
              "P3"
            ]
          ]
        }
      ],
      "byes": [
        "P5",
        "P11",
        "P10"
      ]
    },
    {
      "roundNumber": 10,
      "matches": [
        {
          "court": 1,
          "teams": [
            [
              "P10",
              "P1"
            ],
            [
              "P2",
              "P8"
            ]
          ]
        },
        {
          "court": 2,
          "teams": [
            [
              "P5",
              "P6"
            ],
            [
              "P11",
              "P7"
            ]
          ]
        }
      ],
      "byes": [
        "P9",
        "P4",
        "P3"
      ]
    },
    {
      "roundNumber": 11,
      "matches": [
        {
          "court": 1,
          "teams": [
            [
              "P3",
              "P5"
            ],
            [
              "P6",
              "P1"
            ]
          ]
        },
        {
          "court": 2,
          "teams": [
            [
              "P9",
              "P10"
            ],
            [
              "P4",
              "P11"
            ]
          ]
        }
      ],
      "byes": [
        "P2",
        "P8",
        "P7"
      ]
    }
  ]
}
