// Generated by scheduler/engine/sitout-generate.mjs: do not edit by hand.
window.schedule23p23r = {
  "playerCount": 23,
  "totalRounds": 23,
  "players": [
    "P1",
    "P2",
    "P3",
    "P4",
    "P5",
    "P6",
    "P7",
    "P8",
    "P9",
    "P10",
    "P11",
    "P12",
    "P13",
    "P14",
    "P15",
    "P16",
    "P17",
    "P18",
    "P19",
    "P20",
    "P21",
    "P22",
    "P23"
  ],
  "rounds": [
    {
      "roundNumber": 1,
      "matches": [
        {
          "court": 1,
          "teams": [
            [
              "P4",
              "P18"
            ],
            [
              "P20",
              "P23"
            ]
          ]
        },
        {
          "court": 2,
          "teams": [
            [
              "P22",
              "P12"
            ],
            [
              "P1",
              "P16"
            ]
          ]
        },
        {
          "court": 3,
          "teams": [
            [
              "P5",
              "P9"
            ],
            [
              "P19",
              "P8"
            ]
          ]
        },
        {
          "court": 4,
          "teams": [
            [
              "P11",
              "P17"
            ],
            [
              "P3",
              "P10"
            ]
          ]
        },
        {
          "court": 5,
          "teams": [
            [
              "P2",
              "P7"
            ],
            [
              "P15",
              "P13"
            ]
          ]
        }
      ],
      "byes": [
        "P14",
        "P6",
        "P21"
      ]
    },
    {
      "roundNumber": 2,
      "matches": [
        {
          "court": 1,
          "teams": [
            [
              "P3",
              "P8"
            ],
            [
              "P16",
              "P14"
            ]
          ]
        },
        {
          "court": 2,
          "teams": [
            [
              "P23",
              "P13"
            ],
            [
              "P2",
              "P17"
            ]
          ]
        },
        {
          "court": 3,
          "teams": [
            [
              "P12",
              "P18"
            ],
            [
              "P4",
              "P11"
            ]
          ]
        },
        {
          "court": 4,
          "teams": [
            [
              "P5",
              "P19"
            ],
            [
              "P21",
              "P1"
            ]
          ]
        },
        {
          "court": 5,
          "teams": [
            [
              "P6",
              "P10"
            ],
            [
              "P20",
              "P9"
            ]
          ]
        }
      ],
      "byes": [
        "P15",
        "P7",
        "P22"
      ]
    },
    {
      "roundNumber": 3,
      "matches": [
        {
          "court": 1,
          "teams": [
            [
              "P13",
              "P19"
            ],
            [
              "P5",
              "P12"
            ]
          ]
        },
        {
          "court": 2,
          "teams": [
            [
              "P7",
              "P11"
            ],
            [
              "P21",
              "P10"
            ]
          ]
        },
        {
          "court": 3,
          "teams": [
            [
              "P6",
              "P20"
            ],
            [
              "P22",
              "P2"
            ]
          ]
        },
        {
          "court": 4,
          "teams": [
            [
              "P4",
              "P9"
            ],
            [
              "P17",
              "P15"
            ]
          ]
        },
        {
          "court": 5,
          "teams": [
            [
              "P1",
              "P14"
            ],
            [
              "P3",
              "P18"
            ]
          ]
        }
      ],
      "byes": [
        "P16",
        "P8",
        "P23"
      ]
    },
    {
      "roundNumber": 4,
      "matches": [
        {
          "court": 1,
          "teams": [
            [
              "P2",
              "P15"
            ],
            [
              "P4",
              "P19"
            ]
          ]
        },
        {
          "court": 2,
          "teams": [
            [
              "P5",
              "P10"
            ],
            [
              "P18",
              "P16"
            ]
          ]
        },
        {
          "court": 3,
          "teams": [
            [
              "P7",
              "P21"
            ],
            [
              "P23",
              "P3"
            ]
          ]
        },
        {
          "court": 4,
          "teams": [
            [
              "P14",
              "P20"
            ],
            [
              "P6",
              "P13"
            ]
          ]
        },
        {
          "court": 5,
          "teams": [
            [
              "P8",
              "P12"
            ],
            [
              "P22",
              "P11"
            ]
          ]
        }
      ],
      "byes": [
        "P17",
        "P9",
        "P1"
      ]
    },
    {
      "roundNumber": 5,
      "matches": [
        {
          "court": 1,
          "teams": [
            [
              "P15",
              "P21"
            ],
            [
              "P7",
              "P14"
            ]
          ]
        },
        {
          "court": 2,
          "teams": [
            [
              "P8",
              "P22"
            ],
            [
              "P1",
              "P4"
            ]
          ]
        },
        {
          "court": 3,
          "teams": [
            [
              "P3",
              "P16"
            ],
            [
              "P5",
              "P20"
            ]
          ]
        },
        {
          "court": 4,
          "teams": [
            [
              "P9",
              "P13"
            ],
            [
              "P23",
              "P12"
            ]
          ]
        },
        {
          "court": 5,
          "teams": [
            [
              "P6",
              "P11"
            ],
            [
              "P19",
              "P17"
            ]
          ]
        }
      ],
      "byes": [
        "P18",
        "P10",
        "P2"
      ]
    },
    {
      "roundNumber": 6,
      "matches": [
        {
          "court": 1,
          "teams": [
            [
              "P7",
              "P12"
            ],
            [
              "P20",
              "P18"
            ]
          ]
        },
        {
          "court": 2,
          "teams": [
            [
              "P4",
              "P17"
            ],
            [
              "P6",
              "P21"
            ]
          ]
        },
        {
          "court": 3,
          "teams": [
            [
              "P10",
              "P14"
            ],
            [
              "P1",
              "P13"
            ]
          ]
        },
        {
          "court": 4,
          "teams": [
            [
              "P16",
              "P22"
            ],
            [
              "P8",
              "P15"
            ]
          ]
        },
        {
          "court": 5,
          "teams": [
            [
              "P9",
              "P23"
            ],
            [
              "P2",
              "P5"
            ]
          ]
        }
      ],
      "byes": [
        "P19",
        "P11",
        "P3"
      ]
    },
    {
      "roundNumber": 7,
      "matches": [
        {
          "court": 1,
          "teams": [
            [
              "P10",
              "P1"
            ],
            [
              "P3",
              "P6"
            ]
          ]
        },
        {
          "court": 2,
          "teams": [
            [
              "P11",
              "P15"
            ],
            [
              "P2",
              "P14"
            ]
          ]
        },
        {
          "court": 3,
          "teams": [
            [
              "P17",
              "P23"
            ],
            [
              "P9",
              "P16"
            ]
          ]
        },
        {
          "court": 4,
          "teams": [
            [
              "P5",
              "P18"
            ],
            [
              "P7",
              "P22"
            ]
          ]
        },
        {
          "court": 5,
          "teams": [
            [
              "P8",
              "P13"
            ],
            [
              "P21",
              "P19"
            ]
          ]
        }
      ],
      "byes": [
        "P20",
        "P12",
        "P4"
      ]
    },
    {
      "roundNumber": 8,
      "matches": [
        {
          "court": 1,
          "teams": [
            [
              "P9",
              "P14"
            ],
            [
              "P22",
              "P20"
            ]
          ]
        },
        {
          "court": 2,
          "teams": [
            [
              "P6",
              "P19"
            ],
            [
              "P8",
              "P23"
            ]
          ]
        },
        {
          "court": 3,
          "teams": [
            [
              "P18",
              "P1"
            ],
            [
              "P10",
              "P17"
            ]
          ]
        },
        {
          "court": 4,
          "teams": [
            [
              "P11",
              "P2"
            ],
            [
              "P4",
              "P7"
            ]
          ]
        },
        {
          "court": 5,
          "teams": [
            [
              "P12",
              "P16"
            ],
            [
              "P3",
              "P15"
            ]
          ]
        }
      ],
      "byes": [
        "P21",
        "P13",
        "P5"
      ]
    },
    {
      "roundNumber": 9,
      "matches": [
        {
          "court": 1,
          "teams": [
            [
              "P13",
              "P17"
            ],
            [
              "P4",
              "P16"
            ]
          ]
        },
        {
          "court": 2,
          "teams": [
            [
              "P7",
              "P20"
            ],
            [
              "P9",
              "P1"
            ]
          ]
        },
        {
          "court": 3,
          "teams": [
            [
              "P19",
              "P2"
            ],
            [
              "P11",
              "P18"
            ]
          ]
        },
        {
          "court": 4,
          "teams": [
            [
              "P12",
              "P3"
            ],
            [
              "P5",
              "P8"
            ]
          ]
        },
        {
          "court": 5,
          "teams": [
            [
              "P10",
              "P15"
            ],
            [
              "P23",
              "P21"
            ]
          ]
        }
      ],
      "byes": [
        "P22",
        "P14",
        "P6"
      ]
    },
    {
      "roundNumber": 10,
      "matches": [
        {
          "court": 1,
          "teams": [
            [
              "P11",
              "P16"
            ],
            [
              "P1",
              "P22"
            ]
          ]
        },
        {
          "court": 2,
          "teams": [
            [
              "P20",
              "P3"
            ],
            [
              "P12",
              "P19"
            ]
          ]
        },
        {
          "court": 3,
          "teams": [
            [
              "P13",
              "P4"
            ],
            [
              "P6",
              "P9"
            ]
          ]
        },
        {
          "court": 4,
          "teams": [
            [
              "P8",
              "P21"
            ],
            [
              "P10",
              "P2"
            ]
          ]
        },
        {
          "court": 5,
          "teams": [
            [
              "P14",
              "P18"
            ],
            [
              "P5",
              "P17"
            ]
          ]
        }
      ],
      "byes": [
        "P23",
        "P15",
        "P7"
      ]
    },
    {
      "roundNumber": 11,
      "matches": [
        {
          "court": 1,
          "teams": [
            [
              "P12",
              "P17"
            ],
            [
              "P2",
              "P23"
            ]
          ]
        },
        {
          "court": 2,
          "teams": [
            [
              "P9",
              "P22"
            ],
            [
              "P11",
              "P3"
            ]
          ]
        },
        {
          "court": 3,
          "teams": [
            [
              "P14",
              "P5"
            ],
            [
              "P7",
              "P10"
            ]
          ]
        },
        {
          "court": 4,
          "teams": [
            [
              "P15",
              "P19"
            ],
            [
              "P6",
              "P18"
            ]
          ]
        },
        {
          "court": 5,
          "teams": [
            [
              "P21",
              "P4"
            ],
            [
              "P13",
              "P20"
            ]
          ]
        }
      ],
      "byes": [
        "P1",
        "P16",
        "P8"
      ]
    },
    {
      "roundNumber": 12,
      "matches": [
        {
          "court": 1,
          "teams": [
            [
              "P15",
              "P6"
            ],
            [
              "P8",
              "P11"
            ]
          ]
        },
        {
          "court": 2,
          "teams": [
            [
              "P13",
              "P18"
            ],
            [
              "P3",
              "P1"
            ]
          ]
        },
        {
          "court": 3,
          "teams": [
            [
              "P22",
              "P5"
            ],
            [
              "P14",
              "P21"
            ]
          ]
        },
        {
          "court": 4,
          "teams": [
            [
              "P10",
              "P23"
            ],
            [
              "P12",
              "P4"
            ]
          ]
        },
        {
          "court": 5,
          "teams": [
            [
              "P16",
              "P20"
            ],
            [
              "P7",
              "P19"
            ]
          ]
        }
      ],
      "byes": [
        "P2",
        "P17",
        "P9"
      ]
    },
    {
      "roundNumber": 13,
      "matches": [
        {
          "court": 1,
          "teams": [
            [
              "P11",
              "P1"
            ],
            [
              "P13",
              "P5"
            ]
          ]
        },
        {
          "court": 2,
          "teams": [
            [
              "P14",
              "P19"
            ],
            [
              "P4",
              "P2"
            ]
          ]
        },
        {
          "court": 3,
          "teams": [
            [
              "P23",
              "P6"
            ],
            [
              "P15",
              "P22"
            ]
          ]
        },
        {
          "court": 4,
          "teams": [
            [
              "P17",
              "P21"
            ],
            [
              "P8",
              "P20"
            ]
          ]
        },
        {
          "court": 5,
          "teams": [
            [
              "P16",
              "P7"
            ],
            [
              "P9",
              "P12"
            ]
          ]
        }
      ],
      "byes": [
        "P3",
        "P18",
        "P10"
      ]
    },
    {
      "roundNumber": 14,
      "matches": [
        {
          "court": 1,
          "teams": [
            [
              "P18",
              "P22"
            ],
            [
              "P9",
              "P21"
            ]
          ]
        },
        {
          "court": 2,
          "teams": [
            [
              "P15",
              "P20"
            ],
            [
              "P5",
              "P3"
            ]
          ]
        },
        {
          "court": 3,
          "teams": [
            [
              "P17",
              "P8"
            ],
            [
              "P10",
              "P13"
            ]
          ]
        },
        {
          "court": 4,
          "teams": [
            [
              "P1",
              "P7"
            ],
            [
              "P16",
              "P23"
            ]
          ]
        },
        {
          "court": 5,
          "teams": [
            [
              "P12",
              "P2"
            ],
            [
              "P14",
              "P6"
            ]
          ]
        }
      ],
      "byes": [
        "P4",
        "P19",
        "P11"
      ]
    },
    {
      "roundNumber": 15,
      "matches": [
        {
          "court": 1,
          "teams": [
            [
              "P19",
              "P23"
            ],
            [
              "P10",
              "P22"
            ]
          ]
        },
        {
          "court": 2,
          "teams": [
            [
              "P16",
              "P21"
            ],
            [
              "P6",
              "P4"
            ]
          ]
        },
        {
          "court": 3,
          "teams": [
            [
              "P13",
              "P3"
            ],
            [
              "P15",
              "P7"
            ]
          ]
        },
        {
          "court": 4,
          "teams": [
            [
              "P18",
              "P9"
            ],
            [
              "P11",
              "P14"
            ]
          ]
        },
        {
          "court": 5,
          "teams": [
            [
              "P2",
              "P8"
            ],
            [
              "P17",
              "P1"
            ]
          ]
        }
      ],
      "byes": [
        "P5",
        "P20",
        "P12"
      ]
    },
    {
      "roundNumber": 16,
      "matches": [
        {
          "court": 1,
          "teams": [
            [
              "P3",
              "P9"
            ],
            [
              "P18",
              "P2"
            ]
          ]
        },
        {
          "court": 2,
          "teams": [
            [
              "P19",
              "P10"
            ],
            [
              "P12",
              "P15"
            ]
          ]
        },
        {
          "court": 3,
          "teams": [
            [
              "P14",
              "P4"
            ],
            [
              "P16",
              "P8"
            ]
          ]
        },
        {
          "court": 4,
          "teams": [
            [
              "P20",
              "P1"
            ],
            [
              "P11",
              "P23"
            ]
          ]
        },
        {
          "court": 5,
          "teams": [
            [
              "P17",
              "P22"
            ],
            [
              "P7",
              "P5"
            ]
          ]
        }
      ],
      "byes": [
        "P6",
        "P21",
        "P13"
      ]
    },
    {
      "roundNumber": 17,
      "matches": [
        {
          "court": 1,
          "teams": [
            [
              "P15",
              "P5"
            ],
            [
              "P17",
              "P9"
            ]
          ]
        },
        {
          "court": 2,
          "teams": [
            [
              "P18",
              "P23"
            ],
            [
              "P8",
              "P6"
            ]
          ]
        },
        {
          "court": 3,
          "teams": [
            [
              "P21",
              "P2"
            ],
            [
              "P12",
              "P1"
            ]
          ]
        },
        {
          "court": 4,
          "teams": [
            [
              "P4",
              "P10"
            ],
            [
              "P19",
              "P3"
            ]
          ]
        },
        {
          "court": 5,
          "teams": [
            [
              "P20",
              "P11"
            ],
            [
              "P13",
              "P16"
            ]
          ]
        }
      ],
      "byes": [
        "P7",
        "P22",
        "P14"
      ]
    },
    {
      "roundNumber": 18,
      "matches": [
        {
          "court": 1,
          "teams": [
            [
              "P16",
              "P6"
            ],
            [
              "P18",
              "P10"
            ]
          ]
        },
        {
          "court": 2,
          "teams": [
            [
              "P21",
              "P12"
            ],
            [
              "P14",
              "P17"
            ]
          ]
        },
        {
          "court": 3,
          "teams": [
            [
              "P19",
              "P1"
            ],
            [
              "P9",
              "P7"
            ]
          ]
        },
        {
          "court": 4,
          "teams": [
            [
              "P22",
              "P3"
            ],
            [
              "P13",
              "P2"
            ]
          ]
        },
        {
          "court": 5,
          "teams": [
            [
              "P5",
              "P11"
            ],
            [
              "P20",
              "P4"
            ]
          ]
        }
      ],
      "byes": [
        "P8",
        "P23",
        "P15"
      ]
    },
    {
      "roundNumber": 19,
      "matches": [
        {
          "court": 1,
          "teams": [
            [
              "P17",
              "P7"
            ],
            [
              "P19",
              "P11"
            ]
          ]
        },
        {
          "court": 2,
          "teams": [
            [
              "P22",
              "P13"
            ],
            [
              "P15",
              "P18"
            ]
          ]
        },
        {
          "court": 3,
          "teams": [
            [
              "P20",
              "P2"
            ],
            [
              "P10",
              "P8"
            ]
          ]
        },
        {
          "court": 4,
          "teams": [
            [
              "P6",
              "P12"
            ],
            [
              "P21",
              "P5"
            ]
          ]
        },
        {
          "court": 5,
          "teams": [
            [
              "P23",
              "P4"
            ],
            [
              "P14",
              "P3"
            ]
          ]
        }
      ],
      "byes": [
        "P9",
        "P1",
        "P16"
      ]
    },
    {
      "roundNumber": 20,
      "matches": [
        {
          "court": 1,
          "teams": [
            [
              "P7",
              "P13"
            ],
            [
              "P22",
              "P6"
            ]
          ]
        },
        {
          "court": 2,
          "teams": [
            [
              "P21",
              "P3"
            ],
            [
              "P11",
              "P9"
            ]
          ]
        },
        {
          "court": 3,
          "teams": [
            [
              "P18",
              "P8"
            ],
            [
              "P20",
              "P12"
            ]
          ]
        },
        {
          "court": 4,
          "teams": [
            [
              "P23",
              "P14"
            ],
            [
              "P16",
              "P19"
            ]
          ]
        },
        {
          "court": 5,
          "teams": [
            [
              "P1",
              "P5"
            ],
            [
              "P15",
              "P4"
            ]
          ]
        }
      ],
      "byes": [
        "P10",
        "P2",
        "P17"
      ]
    },
    {
      "roundNumber": 21,
      "matches": [
        {
          "court": 1,
          "teams": [
            [
              "P8",
              "P14"
            ],
            [
              "P23",
              "P7"
            ]
          ]
        },
        {
          "court": 2,
          "teams": [
            [
              "P2",
              "P6"
            ],
            [
              "P16",
              "P5"
            ]
          ]
        },
        {
          "court": 3,
          "teams": [
            [
              "P19",
              "P9"
            ],
            [
              "P21",
              "P13"
            ]
          ]
        },
        {
          "court": 4,
          "teams": [
            [
              "P1",
              "P15"
            ],
            [
              "P17",
              "P20"
            ]
          ]
        },
        {
          "court": 5,
          "teams": [
            [
              "P22",
              "P4"
            ],
            [
              "P12",
              "P10"
            ]
          ]
        }
      ],
      "byes": [
        "P11",
        "P3",
        "P18"
      ]
    },
    {
      "roundNumber": 22,
      "matches": [
        {
          "court": 1,
          "teams": [
            [
              "P23",
              "P5"
            ],
            [
              "P13",
              "P11"
            ]
          ]
        },
        {
          "court": 2,
          "teams": [
            [
              "P20",
              "P10"
            ],
            [
              "P22",
              "P14"
            ]
          ]
        },
        {
          "court": 3,
          "teams": [
            [
              "P3",
              "P7"
            ],
            [
              "P17",
              "P6"
            ]
          ]
        },
        {
          "court": 4,
          "teams": [
            [
              "P2",
              "P16"
            ],
            [
              "P18",
              "P21"
            ]
          ]
        },
        {
          "court": 5,
          "teams": [
            [
              "P9",
              "P15"
            ],
            [
              "P1",
              "P8"
            ]
          ]
        }
      ],
      "byes": [
        "P12",
        "P4",
        "P19"
      ]
    },
    {
      "roundNumber": 23,
      "matches": [
        {
          "court": 1,
          "teams": [
            [
              "P10",
              "P16"
            ],
            [
              "P2",
              "P9"
            ]
          ]
        },
        {
          "court": 2,
          "teams": [
            [
              "P4",
              "P8"
            ],
            [
              "P18",
              "P7"
            ]
          ]
        },
        {
          "court": 3,
          "teams": [
            [
              "P21",
              "P11"
            ],
            [
              "P23",
              "P15"
            ]
          ]
        },
        {
          "court": 4,
          "teams": [
            [
              "P1",
              "P6"
            ],
            [
              "P14",
              "P12"
            ]
          ]
        },
        {
          "court": 5,
          "teams": [
            [
              "P3",
              "P17"
            ],
            [
              "P19",
              "P22"
            ]
          ]
        }
      ],
      "byes": [
        "P13",
        "P5",
        "P20"
      ]
    }
  ]
}
