name: Deploy and 

permissions:
  contents: write

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      # Install http-server and wait-on as dev dependencies (or globally if preferred)
      - name: Install http-server and wait-on
        run: npm install -D http-server wait-on

      # Start the static server in the background on port 8080.
      - name: Start static server
        run: |
          npx http-server . -p 8080 &
          npx wait-on http://localhost:8080

      - name: Install playwright
        run: npx playwright install

      - name: Start static server and run tests
        env:
          BASE_URL: "http://localhost:8080"
        run: |
          pkill -f "http-server" || true
          # Start the static server in the background on port 8080.
          npx http-server . -p 8080 &
          SERVER_PID=$!
          # Wait until the server is ready.
          npx wait-on http://localhost:8080
          # Run Playwright tests (they use BASE_URL from the env)
          npx playwright test
          # Kill the server after tests are done.
          kill $SERVER_PID
      
      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish current workdir (which contains generated content) to GitHub Pages
        uses: rayluo/github-pages-overwriter@v1.3

        with:

          # Optional.
          #
          # Default value "." means the root directory of your project will be published.
          #
          # You can use whatever directory your project uses,
          # for example "wwwroot" (without leading "./").
          # Such a directory does *not* have to already exist in your repo,
          # it could be an output directory created dynamically
          # by your static website builder.
          source-directory: web

          # Optional. Default value "gh-pages".
          # It specifies the temporary branch which hosts the static website.
          # Each build will REMOVE this branch and replace it with new content.
          # (If you want to keep your old "gh-pages" branch,
          # you should define a different target branch for this GPO action to work with.)
          target-branch: gh-pages

          

  
      

     