name: Deploy and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      # If you have a build step (for example, if using webpack or similar), run it here:
      # - name: Build project
      #   run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # adjust if your site is in a subdirectory

  test:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Install playwright
        run: npx playwright install

      # Optionally, add a wait step if the deployed site needs a moment to be live.
      - name: Wait for deployment to be available
        run: sleep 20

      - name: Run Playwright Tests
        env:
          BASE_URL: "https://kjelltillstrand.github.io/padeltournament/"  # replace with your actual URL
        run: npx playwright test
